
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogisticsService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733/Design_Time_Addresses/WinkelService/LogisticsService/?wsdl")
public class LogisticsService
    extends Service
{

    private final static URL LOGISTICSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGISTICSSERVICE_EXCEPTION;
    private final static QName LOGISTICSSERVICE_QNAME = new QName("http://tempuri.org/", "LogisticsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8733/Design_Time_Addresses/WinkelService/LogisticsService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGISTICSSERVICE_WSDL_LOCATION = url;
        LOGISTICSSERVICE_EXCEPTION = e;
    }

    public LogisticsService() {
        super(__getWsdlLocation(), LOGISTICSSERVICE_QNAME);
    }

    public LogisticsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGISTICSSERVICE_QNAME, features);
    }

    public LogisticsService(URL wsdlLocation) {
        super(wsdlLocation, LOGISTICSSERVICE_QNAME);
    }

    public LogisticsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGISTICSSERVICE_QNAME, features);
    }

    public LogisticsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogisticsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ILogisticsService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILogisticsService")
    public ILogisticsService getBasicHttpBindingILogisticsService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ILogisticsService"), ILogisticsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILogisticsService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILogisticsService")
    public ILogisticsService getBasicHttpBindingILogisticsService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ILogisticsService"), ILogisticsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGISTICSSERVICE_EXCEPTION!= null) {
            throw LOGISTICSSERVICE_EXCEPTION;
        }
        return LOGISTICSSERVICE_WSDL_LOCATION;
    }

}
