//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BoughtProducts = new HashSet<BoughtProduct>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int stock { get; set; }
        public int price { get; set; }
    
        public virtual ICollection<BoughtProduct> BoughtProducts { get; set; }
    }
}
