
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.winkelservice.ArrayOfProduct;
import org.datacontract.schemas._2004._07.winkelservice.Product;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IProductService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.winkelservice.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IProductService {


    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.winkelservice.ArrayOfProduct
     */
    @WebMethod(action = "http://tempuri.org/IProductService/getAllProducts")
    @WebResult(name = "getAllProductsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllProductsResponse")
    public ArrayOfProduct getAllProducts();

    /**
     * 
     * @param productId
     * @return
     *     returns org.datacontract.schemas._2004._07.winkelservice.Product
     */
    @WebMethod(action = "http://tempuri.org/IProductService/getProductById")
    @WebResult(name = "getProductByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductByIdResponse")
    public Product getProductById(
        @WebParam(name = "productId", targetNamespace = "http://tempuri.org/")
        Integer productId);

    /**
     * 
     * @param price
     * @param name
     * @param stock
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/IProductService/addProduct")
    @WebResult(name = "addProductResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddProductResponse")
    public Boolean addProduct(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "stock", targetNamespace = "http://tempuri.org/")
        Integer stock,
        @WebParam(name = "price", targetNamespace = "http://tempuri.org/")
        Integer price);

}
