
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.winkelservice.ArrayOfBoughtProduct;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILogisticsService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.winkelservice.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ILogisticsService {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.datacontract.schemas._2004._07.winkelservice.ArrayOfBoughtProduct
     */
    @WebMethod(action = "http://tempuri.org/ILogisticsService/getBoughtProducts")
    @WebResult(name = "getBoughtProductsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getBoughtProducts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBoughtProducts")
    @ResponseWrapper(localName = "getBoughtProductsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBoughtProductsResponse")
    public ArrayOfBoughtProduct getBoughtProducts(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param amount
     * @param password
     * @param productId
     * @param username
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/ILogisticsService/buyProduct")
    @WebResult(name = "buyProductResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "buyProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyProduct")
    @ResponseWrapper(localName = "buyProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyProductResponse")
    public Boolean buyProduct(
        @WebParam(name = "productId", targetNamespace = "http://tempuri.org/")
        Integer productId,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Integer amount,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param amount
     * @param productId
     */
    @WebMethod(action = "http://tempuri.org/ILogisticsService/updateStockByProdId")
    @RequestWrapper(localName = "updateStockByProdId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateStockByProdId")
    @ResponseWrapper(localName = "updateStockByProdIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateStockByProdIdResponse")
    public void updateStockByProdId(
        @WebParam(name = "productId", targetNamespace = "http://tempuri.org/")
        Integer productId,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Integer amount);

}
